# Generated by Django 5.0.6 on 2024-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
